// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package kafkamodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import org.apache.kafka.clients.producer.*;

public class Send extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String ProducerName;
	private java.lang.String Topic;
	private java.lang.String Key;
	private java.lang.String Value;

	public Send(IContext context, java.lang.String ProducerName, java.lang.String Topic, java.lang.String Key, java.lang.String Value)
	{
		super(context);
		this.ProducerName = ProducerName;
		this.Topic = Topic;
		this.Key = Key;
		this.Value = Value;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		KafkaProducerWrapper producer = KafkaProducerRepository.get(ProducerName);

		producer.send(new ProducerRecord<String, String>(Topic, Key, Value));
		
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "Send";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
