// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package kafkamodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class StartProcessor extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String ProcessorName;
	private IMendixObject __Config;
	private kafkamodule.proxies.StreamsConfig Config;
	private java.lang.String FromTopic;
	private java.lang.String ToTopic;
	private java.lang.String OnProcess;

	public StartProcessor(IContext context, java.lang.String ProcessorName, IMendixObject Config, java.lang.String FromTopic, java.lang.String ToTopic, java.lang.String OnProcess)
	{
		super(context);
		this.ProcessorName = ProcessorName;
		this.__Config = Config;
		this.FromTopic = FromTopic;
		this.ToTopic = ToTopic;
		this.OnProcess = OnProcess;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.Config = __Config == null ? null : kafkamodule.proxies.StreamsConfig.initialize(getContext(), __Config);

		// BEGIN USER CODE
		KafkaProcessor processor = new KafkaProcessor(__Config, getContext(), FromTopic, ToTopic, OnProcess); 
		processor.start();
		KafkaProcessorRepository.put(ProcessorName, processor);
		
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "StartProcessor";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
