// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package kafkamodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import kafkamodule.impl.KafkaConsumerRepository;
import kafkamodule.impl.KafkaConsumerRunner;
import kafkamodule.impl.KafkaModule;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * This action will always return true.
 */
public class StartConsumer extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __consumer;
	private kafkamodule.proxies.Consumer consumer;

	public StartConsumer(IContext context, IMendixObject consumer)
	{
		super(context);
		this.__consumer = consumer;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.consumer = __consumer == null ? null : kafkamodule.proxies.Consumer.initialize(getContext(), __consumer);

		// BEGIN USER CODE
		for (int i = 0; i < consumer.getConsumersPerInstance(); i++) {
			KafkaConsumerRunner consumerRunner = new KafkaConsumerRunner(consumer, getContext()); 
			KafkaConsumerRepository.put(consumer.getName() + "-" + i, consumerRunner);
			new Thread(consumerRunner).start();
			KafkaModule.LOGGER.info("Started Kafka consumer " + consumer.getName() + "-" + i);
		}
		
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "StartConsumer";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
