// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package kafkamodule.actions;

import java.util.*;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class StartConsumer extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String ConsumerName;
	private IMendixObject __Config;
	private kafkamodule.proxies.ConsumerConfig Config;
	private java.lang.String Topic;
	private java.lang.String OnReceive;

	public StartConsumer(IContext context, java.lang.String ConsumerName, IMendixObject Config, java.lang.String Topic, java.lang.String OnReceive)
	{
		super(context);
		this.ConsumerName = ConsumerName;
		this.__Config = Config;
		this.Topic = Topic;
		this.OnReceive = OnReceive;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.Config = __Config == null ? null : kafkamodule.proxies.ConsumerConfig.initialize(getContext(), __Config);

		// BEGIN USER CODE
		KafkaConsumerRunner consumer = new KafkaConsumerRunner(__Config, Topic, OnReceive, getContext()); 
		KafkaConsumerRepository.put(ConsumerName, consumer);
		new Thread(consumer).start();
		
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "StartConsumer";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
