// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package kafkamodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * Stops a certain Kafka consumer.
 * 
 * This action will always return true.
 */
public class StopConsumer extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String ConsumerName;

	public StopConsumer(IContext context, java.lang.String ConsumerName)
	{
		super(context);
		this.ConsumerName = ConsumerName;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		KafkaConsumerRepository.stop(ConsumerName);
		
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "StopConsumer";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
