// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package kafka.proxies;

/**
 * General Kafka configuration options
 */
public class Config
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject configMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Kafka.Config";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		bootstrap_servers("bootstrap_servers"),
		connections_max_idle_ms("connections_max_idle_ms"),
		receive_buffer_bytes("receive_buffer_bytes"),
		request_timeout_ms("request_timeout_ms"),
		sasl_jaas_config("sasl_jaas_config"),
		sasl_kerberos_service_name("sasl_kerberos_service_name"),
		sasl_mechanism("sasl_mechanism"),
		security_protocol("security_protocol"),
		send_buffer_bytes("send_buffer_bytes"),
		ssl_enabled_protocols("ssl_enabled_protocols"),
		ssl_keystore_type("ssl_keystore_type"),
		ssl_protocol("ssl_protocol"),
		ssl_provider("ssl_provider"),
		ssl_truststore_type("ssl_truststore_type"),
		client_id("client_id"),
		interceptor_classes("interceptor_classes"),
		metadata_max_age_ms("metadata_max_age_ms"),
		metric_reporters("metric_reporters"),
		metrics_num_samples("metrics_num_samples"),
		metrics_recording_level("metrics_recording_level"),
		metrics_sample_window_ms("metrics_sample_window_ms"),
		reconnect_backoff_max_ms("reconnect_backoff_max_ms"),
		reconnect_backoff_ms("reconnect_backoff_ms"),
		retry_backoff_ms("retry_backoff_ms"),
		sasl_kerberos_kinit_cmd("sasl_kerberos_kinit_cmd"),
		sasl_kerberos_min_time_before_relogin("sasl_kerberos_min_time_before_relogin"),
		sasl_kerberos_ticket_renew_jitter("sasl_kerberos_ticket_renew_jitter"),
		sasl_kerberos_ticket_renew_window_factor("sasl_kerberos_ticket_renew_window_factor"),
		ssl_cipher_suites("ssl_cipher_suites"),
		ssl_endpoint_identification_algorithm("ssl_endpoint_identification_algorithm"),
		ssl_keymanager_algorithm("ssl_keymanager_algorithm"),
		ssl_secure_random_implementation("ssl_secure_random_implementation"),
		ssl_trustmanager_algorithm("ssl_trustmanager_algorithm"),
		Server_Config("Kafka.Server_Config");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Config(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Kafka.Config"));
	}

	protected Config(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject configMendixObject)
	{
		if (configMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Kafka.Config", configMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Kafka.Config");

		this.configMendixObject = configMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Config.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static kafka.proxies.Config initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return kafka.proxies.Config.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static kafka.proxies.Config initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("Kafka.StreamsConfig", mendixObject.getType()))
			return kafka.proxies.StreamsConfig.initialize(context, mendixObject);

		return new kafka.proxies.Config(context, mendixObject);
	}

	public static kafka.proxies.Config load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return kafka.proxies.Config.initialize(context, mendixObject);
	}

	public static java.util.List<? extends kafka.proxies.Config> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<kafka.proxies.Config> result = new java.util.ArrayList<kafka.proxies.Config>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Kafka.Config" + xpathConstraint))
			result.add(kafka.proxies.Config.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of bootstrap_servers
	 */
	public final java.lang.String getbootstrap_servers()
	{
		return getbootstrap_servers(getContext());
	}

	/**
	 * @param context
	 * @return value of bootstrap_servers
	 */
	public final java.lang.String getbootstrap_servers(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.bootstrap_servers.toString());
	}

	/**
	 * Set value of bootstrap_servers
	 * @param bootstrap_servers
	 */
	public final void setbootstrap_servers(java.lang.String bootstrap_servers)
	{
		setbootstrap_servers(getContext(), bootstrap_servers);
	}

	/**
	 * Set value of bootstrap_servers
	 * @param context
	 * @param bootstrap_servers
	 */
	public final void setbootstrap_servers(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String bootstrap_servers)
	{
		getMendixObject().setValue(context, MemberNames.bootstrap_servers.toString(), bootstrap_servers);
	}

	/**
	 * @return value of connections_max_idle_ms
	 */
	public final java.lang.Long getconnections_max_idle_ms()
	{
		return getconnections_max_idle_ms(getContext());
	}

	/**
	 * @param context
	 * @return value of connections_max_idle_ms
	 */
	public final java.lang.Long getconnections_max_idle_ms(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.connections_max_idle_ms.toString());
	}

	/**
	 * Set value of connections_max_idle_ms
	 * @param connections_max_idle_ms
	 */
	public final void setconnections_max_idle_ms(java.lang.Long connections_max_idle_ms)
	{
		setconnections_max_idle_ms(getContext(), connections_max_idle_ms);
	}

	/**
	 * Set value of connections_max_idle_ms
	 * @param context
	 * @param connections_max_idle_ms
	 */
	public final void setconnections_max_idle_ms(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long connections_max_idle_ms)
	{
		getMendixObject().setValue(context, MemberNames.connections_max_idle_ms.toString(), connections_max_idle_ms);
	}

	/**
	 * @return value of receive_buffer_bytes
	 */
	public final java.lang.Integer getreceive_buffer_bytes()
	{
		return getreceive_buffer_bytes(getContext());
	}

	/**
	 * @param context
	 * @return value of receive_buffer_bytes
	 */
	public final java.lang.Integer getreceive_buffer_bytes(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.receive_buffer_bytes.toString());
	}

	/**
	 * Set value of receive_buffer_bytes
	 * @param receive_buffer_bytes
	 */
	public final void setreceive_buffer_bytes(java.lang.Integer receive_buffer_bytes)
	{
		setreceive_buffer_bytes(getContext(), receive_buffer_bytes);
	}

	/**
	 * Set value of receive_buffer_bytes
	 * @param context
	 * @param receive_buffer_bytes
	 */
	public final void setreceive_buffer_bytes(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer receive_buffer_bytes)
	{
		getMendixObject().setValue(context, MemberNames.receive_buffer_bytes.toString(), receive_buffer_bytes);
	}

	/**
	 * @return value of request_timeout_ms
	 */
	public final java.lang.Integer getrequest_timeout_ms()
	{
		return getrequest_timeout_ms(getContext());
	}

	/**
	 * @param context
	 * @return value of request_timeout_ms
	 */
	public final java.lang.Integer getrequest_timeout_ms(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.request_timeout_ms.toString());
	}

	/**
	 * Set value of request_timeout_ms
	 * @param request_timeout_ms
	 */
	public final void setrequest_timeout_ms(java.lang.Integer request_timeout_ms)
	{
		setrequest_timeout_ms(getContext(), request_timeout_ms);
	}

	/**
	 * Set value of request_timeout_ms
	 * @param context
	 * @param request_timeout_ms
	 */
	public final void setrequest_timeout_ms(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer request_timeout_ms)
	{
		getMendixObject().setValue(context, MemberNames.request_timeout_ms.toString(), request_timeout_ms);
	}

	/**
	 * @return value of sasl_jaas_config
	 */
	public final java.lang.String getsasl_jaas_config()
	{
		return getsasl_jaas_config(getContext());
	}

	/**
	 * @param context
	 * @return value of sasl_jaas_config
	 */
	public final java.lang.String getsasl_jaas_config(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.sasl_jaas_config.toString());
	}

	/**
	 * Set value of sasl_jaas_config
	 * @param sasl_jaas_config
	 */
	public final void setsasl_jaas_config(java.lang.String sasl_jaas_config)
	{
		setsasl_jaas_config(getContext(), sasl_jaas_config);
	}

	/**
	 * Set value of sasl_jaas_config
	 * @param context
	 * @param sasl_jaas_config
	 */
	public final void setsasl_jaas_config(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sasl_jaas_config)
	{
		getMendixObject().setValue(context, MemberNames.sasl_jaas_config.toString(), sasl_jaas_config);
	}

	/**
	 * @return value of sasl_kerberos_service_name
	 */
	public final java.lang.String getsasl_kerberos_service_name()
	{
		return getsasl_kerberos_service_name(getContext());
	}

	/**
	 * @param context
	 * @return value of sasl_kerberos_service_name
	 */
	public final java.lang.String getsasl_kerberos_service_name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.sasl_kerberos_service_name.toString());
	}

	/**
	 * Set value of sasl_kerberos_service_name
	 * @param sasl_kerberos_service_name
	 */
	public final void setsasl_kerberos_service_name(java.lang.String sasl_kerberos_service_name)
	{
		setsasl_kerberos_service_name(getContext(), sasl_kerberos_service_name);
	}

	/**
	 * Set value of sasl_kerberos_service_name
	 * @param context
	 * @param sasl_kerberos_service_name
	 */
	public final void setsasl_kerberos_service_name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sasl_kerberos_service_name)
	{
		getMendixObject().setValue(context, MemberNames.sasl_kerberos_service_name.toString(), sasl_kerberos_service_name);
	}

	/**
	 * @return value of sasl_mechanism
	 */
	public final java.lang.String getsasl_mechanism()
	{
		return getsasl_mechanism(getContext());
	}

	/**
	 * @param context
	 * @return value of sasl_mechanism
	 */
	public final java.lang.String getsasl_mechanism(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.sasl_mechanism.toString());
	}

	/**
	 * Set value of sasl_mechanism
	 * @param sasl_mechanism
	 */
	public final void setsasl_mechanism(java.lang.String sasl_mechanism)
	{
		setsasl_mechanism(getContext(), sasl_mechanism);
	}

	/**
	 * Set value of sasl_mechanism
	 * @param context
	 * @param sasl_mechanism
	 */
	public final void setsasl_mechanism(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sasl_mechanism)
	{
		getMendixObject().setValue(context, MemberNames.sasl_mechanism.toString(), sasl_mechanism);
	}

	/**
	 * @return value of security_protocol
	 */
	public final java.lang.String getsecurity_protocol()
	{
		return getsecurity_protocol(getContext());
	}

	/**
	 * @param context
	 * @return value of security_protocol
	 */
	public final java.lang.String getsecurity_protocol(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.security_protocol.toString());
	}

	/**
	 * Set value of security_protocol
	 * @param security_protocol
	 */
	public final void setsecurity_protocol(java.lang.String security_protocol)
	{
		setsecurity_protocol(getContext(), security_protocol);
	}

	/**
	 * Set value of security_protocol
	 * @param context
	 * @param security_protocol
	 */
	public final void setsecurity_protocol(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String security_protocol)
	{
		getMendixObject().setValue(context, MemberNames.security_protocol.toString(), security_protocol);
	}

	/**
	 * @return value of send_buffer_bytes
	 */
	public final java.lang.Integer getsend_buffer_bytes()
	{
		return getsend_buffer_bytes(getContext());
	}

	/**
	 * @param context
	 * @return value of send_buffer_bytes
	 */
	public final java.lang.Integer getsend_buffer_bytes(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.send_buffer_bytes.toString());
	}

	/**
	 * Set value of send_buffer_bytes
	 * @param send_buffer_bytes
	 */
	public final void setsend_buffer_bytes(java.lang.Integer send_buffer_bytes)
	{
		setsend_buffer_bytes(getContext(), send_buffer_bytes);
	}

	/**
	 * Set value of send_buffer_bytes
	 * @param context
	 * @param send_buffer_bytes
	 */
	public final void setsend_buffer_bytes(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer send_buffer_bytes)
	{
		getMendixObject().setValue(context, MemberNames.send_buffer_bytes.toString(), send_buffer_bytes);
	}

	/**
	 * @return value of ssl_enabled_protocols
	 */
	public final java.lang.String getssl_enabled_protocols()
	{
		return getssl_enabled_protocols(getContext());
	}

	/**
	 * @param context
	 * @return value of ssl_enabled_protocols
	 */
	public final java.lang.String getssl_enabled_protocols(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ssl_enabled_protocols.toString());
	}

	/**
	 * Set value of ssl_enabled_protocols
	 * @param ssl_enabled_protocols
	 */
	public final void setssl_enabled_protocols(java.lang.String ssl_enabled_protocols)
	{
		setssl_enabled_protocols(getContext(), ssl_enabled_protocols);
	}

	/**
	 * Set value of ssl_enabled_protocols
	 * @param context
	 * @param ssl_enabled_protocols
	 */
	public final void setssl_enabled_protocols(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ssl_enabled_protocols)
	{
		getMendixObject().setValue(context, MemberNames.ssl_enabled_protocols.toString(), ssl_enabled_protocols);
	}

	/**
	 * @return value of ssl_keystore_type
	 */
	public final java.lang.String getssl_keystore_type()
	{
		return getssl_keystore_type(getContext());
	}

	/**
	 * @param context
	 * @return value of ssl_keystore_type
	 */
	public final java.lang.String getssl_keystore_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ssl_keystore_type.toString());
	}

	/**
	 * Set value of ssl_keystore_type
	 * @param ssl_keystore_type
	 */
	public final void setssl_keystore_type(java.lang.String ssl_keystore_type)
	{
		setssl_keystore_type(getContext(), ssl_keystore_type);
	}

	/**
	 * Set value of ssl_keystore_type
	 * @param context
	 * @param ssl_keystore_type
	 */
	public final void setssl_keystore_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ssl_keystore_type)
	{
		getMendixObject().setValue(context, MemberNames.ssl_keystore_type.toString(), ssl_keystore_type);
	}

	/**
	 * @return value of ssl_protocol
	 */
	public final java.lang.String getssl_protocol()
	{
		return getssl_protocol(getContext());
	}

	/**
	 * @param context
	 * @return value of ssl_protocol
	 */
	public final java.lang.String getssl_protocol(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ssl_protocol.toString());
	}

	/**
	 * Set value of ssl_protocol
	 * @param ssl_protocol
	 */
	public final void setssl_protocol(java.lang.String ssl_protocol)
	{
		setssl_protocol(getContext(), ssl_protocol);
	}

	/**
	 * Set value of ssl_protocol
	 * @param context
	 * @param ssl_protocol
	 */
	public final void setssl_protocol(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ssl_protocol)
	{
		getMendixObject().setValue(context, MemberNames.ssl_protocol.toString(), ssl_protocol);
	}

	/**
	 * @return value of ssl_provider
	 */
	public final java.lang.String getssl_provider()
	{
		return getssl_provider(getContext());
	}

	/**
	 * @param context
	 * @return value of ssl_provider
	 */
	public final java.lang.String getssl_provider(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ssl_provider.toString());
	}

	/**
	 * Set value of ssl_provider
	 * @param ssl_provider
	 */
	public final void setssl_provider(java.lang.String ssl_provider)
	{
		setssl_provider(getContext(), ssl_provider);
	}

	/**
	 * Set value of ssl_provider
	 * @param context
	 * @param ssl_provider
	 */
	public final void setssl_provider(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ssl_provider)
	{
		getMendixObject().setValue(context, MemberNames.ssl_provider.toString(), ssl_provider);
	}

	/**
	 * @return value of ssl_truststore_type
	 */
	public final java.lang.String getssl_truststore_type()
	{
		return getssl_truststore_type(getContext());
	}

	/**
	 * @param context
	 * @return value of ssl_truststore_type
	 */
	public final java.lang.String getssl_truststore_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ssl_truststore_type.toString());
	}

	/**
	 * Set value of ssl_truststore_type
	 * @param ssl_truststore_type
	 */
	public final void setssl_truststore_type(java.lang.String ssl_truststore_type)
	{
		setssl_truststore_type(getContext(), ssl_truststore_type);
	}

	/**
	 * Set value of ssl_truststore_type
	 * @param context
	 * @param ssl_truststore_type
	 */
	public final void setssl_truststore_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ssl_truststore_type)
	{
		getMendixObject().setValue(context, MemberNames.ssl_truststore_type.toString(), ssl_truststore_type);
	}

	/**
	 * @return value of client_id
	 */
	public final java.lang.String getclient_id()
	{
		return getclient_id(getContext());
	}

	/**
	 * @param context
	 * @return value of client_id
	 */
	public final java.lang.String getclient_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.client_id.toString());
	}

	/**
	 * Set value of client_id
	 * @param client_id
	 */
	public final void setclient_id(java.lang.String client_id)
	{
		setclient_id(getContext(), client_id);
	}

	/**
	 * Set value of client_id
	 * @param context
	 * @param client_id
	 */
	public final void setclient_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String client_id)
	{
		getMendixObject().setValue(context, MemberNames.client_id.toString(), client_id);
	}

	/**
	 * @return value of interceptor_classes
	 */
	public final java.lang.String getinterceptor_classes()
	{
		return getinterceptor_classes(getContext());
	}

	/**
	 * @param context
	 * @return value of interceptor_classes
	 */
	public final java.lang.String getinterceptor_classes(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.interceptor_classes.toString());
	}

	/**
	 * Set value of interceptor_classes
	 * @param interceptor_classes
	 */
	public final void setinterceptor_classes(java.lang.String interceptor_classes)
	{
		setinterceptor_classes(getContext(), interceptor_classes);
	}

	/**
	 * Set value of interceptor_classes
	 * @param context
	 * @param interceptor_classes
	 */
	public final void setinterceptor_classes(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String interceptor_classes)
	{
		getMendixObject().setValue(context, MemberNames.interceptor_classes.toString(), interceptor_classes);
	}

	/**
	 * @return value of metadata_max_age_ms
	 */
	public final java.lang.Long getmetadata_max_age_ms()
	{
		return getmetadata_max_age_ms(getContext());
	}

	/**
	 * @param context
	 * @return value of metadata_max_age_ms
	 */
	public final java.lang.Long getmetadata_max_age_ms(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.metadata_max_age_ms.toString());
	}

	/**
	 * Set value of metadata_max_age_ms
	 * @param metadata_max_age_ms
	 */
	public final void setmetadata_max_age_ms(java.lang.Long metadata_max_age_ms)
	{
		setmetadata_max_age_ms(getContext(), metadata_max_age_ms);
	}

	/**
	 * Set value of metadata_max_age_ms
	 * @param context
	 * @param metadata_max_age_ms
	 */
	public final void setmetadata_max_age_ms(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long metadata_max_age_ms)
	{
		getMendixObject().setValue(context, MemberNames.metadata_max_age_ms.toString(), metadata_max_age_ms);
	}

	/**
	 * @return value of metric_reporters
	 */
	public final java.lang.String getmetric_reporters()
	{
		return getmetric_reporters(getContext());
	}

	/**
	 * @param context
	 * @return value of metric_reporters
	 */
	public final java.lang.String getmetric_reporters(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.metric_reporters.toString());
	}

	/**
	 * Set value of metric_reporters
	 * @param metric_reporters
	 */
	public final void setmetric_reporters(java.lang.String metric_reporters)
	{
		setmetric_reporters(getContext(), metric_reporters);
	}

	/**
	 * Set value of metric_reporters
	 * @param context
	 * @param metric_reporters
	 */
	public final void setmetric_reporters(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String metric_reporters)
	{
		getMendixObject().setValue(context, MemberNames.metric_reporters.toString(), metric_reporters);
	}

	/**
	 * @return value of metrics_num_samples
	 */
	public final java.lang.Integer getmetrics_num_samples()
	{
		return getmetrics_num_samples(getContext());
	}

	/**
	 * @param context
	 * @return value of metrics_num_samples
	 */
	public final java.lang.Integer getmetrics_num_samples(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.metrics_num_samples.toString());
	}

	/**
	 * Set value of metrics_num_samples
	 * @param metrics_num_samples
	 */
	public final void setmetrics_num_samples(java.lang.Integer metrics_num_samples)
	{
		setmetrics_num_samples(getContext(), metrics_num_samples);
	}

	/**
	 * Set value of metrics_num_samples
	 * @param context
	 * @param metrics_num_samples
	 */
	public final void setmetrics_num_samples(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer metrics_num_samples)
	{
		getMendixObject().setValue(context, MemberNames.metrics_num_samples.toString(), metrics_num_samples);
	}

	/**
	 * @return value of metrics_recording_level
	 */
	public final java.lang.String getmetrics_recording_level()
	{
		return getmetrics_recording_level(getContext());
	}

	/**
	 * @param context
	 * @return value of metrics_recording_level
	 */
	public final java.lang.String getmetrics_recording_level(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.metrics_recording_level.toString());
	}

	/**
	 * Set value of metrics_recording_level
	 * @param metrics_recording_level
	 */
	public final void setmetrics_recording_level(java.lang.String metrics_recording_level)
	{
		setmetrics_recording_level(getContext(), metrics_recording_level);
	}

	/**
	 * Set value of metrics_recording_level
	 * @param context
	 * @param metrics_recording_level
	 */
	public final void setmetrics_recording_level(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String metrics_recording_level)
	{
		getMendixObject().setValue(context, MemberNames.metrics_recording_level.toString(), metrics_recording_level);
	}

	/**
	 * @return value of metrics_sample_window_ms
	 */
	public final java.lang.Long getmetrics_sample_window_ms()
	{
		return getmetrics_sample_window_ms(getContext());
	}

	/**
	 * @param context
	 * @return value of metrics_sample_window_ms
	 */
	public final java.lang.Long getmetrics_sample_window_ms(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.metrics_sample_window_ms.toString());
	}

	/**
	 * Set value of metrics_sample_window_ms
	 * @param metrics_sample_window_ms
	 */
	public final void setmetrics_sample_window_ms(java.lang.Long metrics_sample_window_ms)
	{
		setmetrics_sample_window_ms(getContext(), metrics_sample_window_ms);
	}

	/**
	 * Set value of metrics_sample_window_ms
	 * @param context
	 * @param metrics_sample_window_ms
	 */
	public final void setmetrics_sample_window_ms(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long metrics_sample_window_ms)
	{
		getMendixObject().setValue(context, MemberNames.metrics_sample_window_ms.toString(), metrics_sample_window_ms);
	}

	/**
	 * @return value of reconnect_backoff_max_ms
	 */
	public final java.lang.Long getreconnect_backoff_max_ms()
	{
		return getreconnect_backoff_max_ms(getContext());
	}

	/**
	 * @param context
	 * @return value of reconnect_backoff_max_ms
	 */
	public final java.lang.Long getreconnect_backoff_max_ms(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.reconnect_backoff_max_ms.toString());
	}

	/**
	 * Set value of reconnect_backoff_max_ms
	 * @param reconnect_backoff_max_ms
	 */
	public final void setreconnect_backoff_max_ms(java.lang.Long reconnect_backoff_max_ms)
	{
		setreconnect_backoff_max_ms(getContext(), reconnect_backoff_max_ms);
	}

	/**
	 * Set value of reconnect_backoff_max_ms
	 * @param context
	 * @param reconnect_backoff_max_ms
	 */
	public final void setreconnect_backoff_max_ms(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long reconnect_backoff_max_ms)
	{
		getMendixObject().setValue(context, MemberNames.reconnect_backoff_max_ms.toString(), reconnect_backoff_max_ms);
	}

	/**
	 * @return value of reconnect_backoff_ms
	 */
	public final java.lang.Long getreconnect_backoff_ms()
	{
		return getreconnect_backoff_ms(getContext());
	}

	/**
	 * @param context
	 * @return value of reconnect_backoff_ms
	 */
	public final java.lang.Long getreconnect_backoff_ms(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.reconnect_backoff_ms.toString());
	}

	/**
	 * Set value of reconnect_backoff_ms
	 * @param reconnect_backoff_ms
	 */
	public final void setreconnect_backoff_ms(java.lang.Long reconnect_backoff_ms)
	{
		setreconnect_backoff_ms(getContext(), reconnect_backoff_ms);
	}

	/**
	 * Set value of reconnect_backoff_ms
	 * @param context
	 * @param reconnect_backoff_ms
	 */
	public final void setreconnect_backoff_ms(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long reconnect_backoff_ms)
	{
		getMendixObject().setValue(context, MemberNames.reconnect_backoff_ms.toString(), reconnect_backoff_ms);
	}

	/**
	 * @return value of retry_backoff_ms
	 */
	public final java.lang.Long getretry_backoff_ms()
	{
		return getretry_backoff_ms(getContext());
	}

	/**
	 * @param context
	 * @return value of retry_backoff_ms
	 */
	public final java.lang.Long getretry_backoff_ms(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.retry_backoff_ms.toString());
	}

	/**
	 * Set value of retry_backoff_ms
	 * @param retry_backoff_ms
	 */
	public final void setretry_backoff_ms(java.lang.Long retry_backoff_ms)
	{
		setretry_backoff_ms(getContext(), retry_backoff_ms);
	}

	/**
	 * Set value of retry_backoff_ms
	 * @param context
	 * @param retry_backoff_ms
	 */
	public final void setretry_backoff_ms(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long retry_backoff_ms)
	{
		getMendixObject().setValue(context, MemberNames.retry_backoff_ms.toString(), retry_backoff_ms);
	}

	/**
	 * @return value of sasl_kerberos_kinit_cmd
	 */
	public final java.lang.String getsasl_kerberos_kinit_cmd()
	{
		return getsasl_kerberos_kinit_cmd(getContext());
	}

	/**
	 * @param context
	 * @return value of sasl_kerberos_kinit_cmd
	 */
	public final java.lang.String getsasl_kerberos_kinit_cmd(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.sasl_kerberos_kinit_cmd.toString());
	}

	/**
	 * Set value of sasl_kerberos_kinit_cmd
	 * @param sasl_kerberos_kinit_cmd
	 */
	public final void setsasl_kerberos_kinit_cmd(java.lang.String sasl_kerberos_kinit_cmd)
	{
		setsasl_kerberos_kinit_cmd(getContext(), sasl_kerberos_kinit_cmd);
	}

	/**
	 * Set value of sasl_kerberos_kinit_cmd
	 * @param context
	 * @param sasl_kerberos_kinit_cmd
	 */
	public final void setsasl_kerberos_kinit_cmd(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sasl_kerberos_kinit_cmd)
	{
		getMendixObject().setValue(context, MemberNames.sasl_kerberos_kinit_cmd.toString(), sasl_kerberos_kinit_cmd);
	}

	/**
	 * @return value of sasl_kerberos_min_time_before_relogin
	 */
	public final java.lang.Long getsasl_kerberos_min_time_before_relogin()
	{
		return getsasl_kerberos_min_time_before_relogin(getContext());
	}

	/**
	 * @param context
	 * @return value of sasl_kerberos_min_time_before_relogin
	 */
	public final java.lang.Long getsasl_kerberos_min_time_before_relogin(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.sasl_kerberos_min_time_before_relogin.toString());
	}

	/**
	 * Set value of sasl_kerberos_min_time_before_relogin
	 * @param sasl_kerberos_min_time_before_relogin
	 */
	public final void setsasl_kerberos_min_time_before_relogin(java.lang.Long sasl_kerberos_min_time_before_relogin)
	{
		setsasl_kerberos_min_time_before_relogin(getContext(), sasl_kerberos_min_time_before_relogin);
	}

	/**
	 * Set value of sasl_kerberos_min_time_before_relogin
	 * @param context
	 * @param sasl_kerberos_min_time_before_relogin
	 */
	public final void setsasl_kerberos_min_time_before_relogin(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long sasl_kerberos_min_time_before_relogin)
	{
		getMendixObject().setValue(context, MemberNames.sasl_kerberos_min_time_before_relogin.toString(), sasl_kerberos_min_time_before_relogin);
	}

	/**
	 * @return value of sasl_kerberos_ticket_renew_jitter
	 */
	public final java.math.BigDecimal getsasl_kerberos_ticket_renew_jitter()
	{
		return getsasl_kerberos_ticket_renew_jitter(getContext());
	}

	/**
	 * @param context
	 * @return value of sasl_kerberos_ticket_renew_jitter
	 */
	public final java.math.BigDecimal getsasl_kerberos_ticket_renew_jitter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.sasl_kerberos_ticket_renew_jitter.toString());
	}

	/**
	 * Set value of sasl_kerberos_ticket_renew_jitter
	 * @param sasl_kerberos_ticket_renew_jitter
	 */
	public final void setsasl_kerberos_ticket_renew_jitter(java.math.BigDecimal sasl_kerberos_ticket_renew_jitter)
	{
		setsasl_kerberos_ticket_renew_jitter(getContext(), sasl_kerberos_ticket_renew_jitter);
	}

	/**
	 * Set value of sasl_kerberos_ticket_renew_jitter
	 * @param context
	 * @param sasl_kerberos_ticket_renew_jitter
	 */
	public final void setsasl_kerberos_ticket_renew_jitter(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal sasl_kerberos_ticket_renew_jitter)
	{
		getMendixObject().setValue(context, MemberNames.sasl_kerberos_ticket_renew_jitter.toString(), sasl_kerberos_ticket_renew_jitter);
	}

	/**
	 * @return value of sasl_kerberos_ticket_renew_window_factor
	 */
	public final java.math.BigDecimal getsasl_kerberos_ticket_renew_window_factor()
	{
		return getsasl_kerberos_ticket_renew_window_factor(getContext());
	}

	/**
	 * @param context
	 * @return value of sasl_kerberos_ticket_renew_window_factor
	 */
	public final java.math.BigDecimal getsasl_kerberos_ticket_renew_window_factor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.sasl_kerberos_ticket_renew_window_factor.toString());
	}

	/**
	 * Set value of sasl_kerberos_ticket_renew_window_factor
	 * @param sasl_kerberos_ticket_renew_window_factor
	 */
	public final void setsasl_kerberos_ticket_renew_window_factor(java.math.BigDecimal sasl_kerberos_ticket_renew_window_factor)
	{
		setsasl_kerberos_ticket_renew_window_factor(getContext(), sasl_kerberos_ticket_renew_window_factor);
	}

	/**
	 * Set value of sasl_kerberos_ticket_renew_window_factor
	 * @param context
	 * @param sasl_kerberos_ticket_renew_window_factor
	 */
	public final void setsasl_kerberos_ticket_renew_window_factor(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal sasl_kerberos_ticket_renew_window_factor)
	{
		getMendixObject().setValue(context, MemberNames.sasl_kerberos_ticket_renew_window_factor.toString(), sasl_kerberos_ticket_renew_window_factor);
	}

	/**
	 * @return value of ssl_cipher_suites
	 */
	public final java.lang.String getssl_cipher_suites()
	{
		return getssl_cipher_suites(getContext());
	}

	/**
	 * @param context
	 * @return value of ssl_cipher_suites
	 */
	public final java.lang.String getssl_cipher_suites(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ssl_cipher_suites.toString());
	}

	/**
	 * Set value of ssl_cipher_suites
	 * @param ssl_cipher_suites
	 */
	public final void setssl_cipher_suites(java.lang.String ssl_cipher_suites)
	{
		setssl_cipher_suites(getContext(), ssl_cipher_suites);
	}

	/**
	 * Set value of ssl_cipher_suites
	 * @param context
	 * @param ssl_cipher_suites
	 */
	public final void setssl_cipher_suites(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ssl_cipher_suites)
	{
		getMendixObject().setValue(context, MemberNames.ssl_cipher_suites.toString(), ssl_cipher_suites);
	}

	/**
	 * @return value of ssl_endpoint_identification_algorithm
	 */
	public final java.lang.String getssl_endpoint_identification_algorithm()
	{
		return getssl_endpoint_identification_algorithm(getContext());
	}

	/**
	 * @param context
	 * @return value of ssl_endpoint_identification_algorithm
	 */
	public final java.lang.String getssl_endpoint_identification_algorithm(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ssl_endpoint_identification_algorithm.toString());
	}

	/**
	 * Set value of ssl_endpoint_identification_algorithm
	 * @param ssl_endpoint_identification_algorithm
	 */
	public final void setssl_endpoint_identification_algorithm(java.lang.String ssl_endpoint_identification_algorithm)
	{
		setssl_endpoint_identification_algorithm(getContext(), ssl_endpoint_identification_algorithm);
	}

	/**
	 * Set value of ssl_endpoint_identification_algorithm
	 * @param context
	 * @param ssl_endpoint_identification_algorithm
	 */
	public final void setssl_endpoint_identification_algorithm(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ssl_endpoint_identification_algorithm)
	{
		getMendixObject().setValue(context, MemberNames.ssl_endpoint_identification_algorithm.toString(), ssl_endpoint_identification_algorithm);
	}

	/**
	 * @return value of ssl_keymanager_algorithm
	 */
	public final java.lang.String getssl_keymanager_algorithm()
	{
		return getssl_keymanager_algorithm(getContext());
	}

	/**
	 * @param context
	 * @return value of ssl_keymanager_algorithm
	 */
	public final java.lang.String getssl_keymanager_algorithm(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ssl_keymanager_algorithm.toString());
	}

	/**
	 * Set value of ssl_keymanager_algorithm
	 * @param ssl_keymanager_algorithm
	 */
	public final void setssl_keymanager_algorithm(java.lang.String ssl_keymanager_algorithm)
	{
		setssl_keymanager_algorithm(getContext(), ssl_keymanager_algorithm);
	}

	/**
	 * Set value of ssl_keymanager_algorithm
	 * @param context
	 * @param ssl_keymanager_algorithm
	 */
	public final void setssl_keymanager_algorithm(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ssl_keymanager_algorithm)
	{
		getMendixObject().setValue(context, MemberNames.ssl_keymanager_algorithm.toString(), ssl_keymanager_algorithm);
	}

	/**
	 * @return value of ssl_secure_random_implementation
	 */
	public final java.lang.String getssl_secure_random_implementation()
	{
		return getssl_secure_random_implementation(getContext());
	}

	/**
	 * @param context
	 * @return value of ssl_secure_random_implementation
	 */
	public final java.lang.String getssl_secure_random_implementation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ssl_secure_random_implementation.toString());
	}

	/**
	 * Set value of ssl_secure_random_implementation
	 * @param ssl_secure_random_implementation
	 */
	public final void setssl_secure_random_implementation(java.lang.String ssl_secure_random_implementation)
	{
		setssl_secure_random_implementation(getContext(), ssl_secure_random_implementation);
	}

	/**
	 * Set value of ssl_secure_random_implementation
	 * @param context
	 * @param ssl_secure_random_implementation
	 */
	public final void setssl_secure_random_implementation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ssl_secure_random_implementation)
	{
		getMendixObject().setValue(context, MemberNames.ssl_secure_random_implementation.toString(), ssl_secure_random_implementation);
	}

	/**
	 * @return value of ssl_trustmanager_algorithm
	 */
	public final java.lang.String getssl_trustmanager_algorithm()
	{
		return getssl_trustmanager_algorithm(getContext());
	}

	/**
	 * @param context
	 * @return value of ssl_trustmanager_algorithm
	 */
	public final java.lang.String getssl_trustmanager_algorithm(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ssl_trustmanager_algorithm.toString());
	}

	/**
	 * Set value of ssl_trustmanager_algorithm
	 * @param ssl_trustmanager_algorithm
	 */
	public final void setssl_trustmanager_algorithm(java.lang.String ssl_trustmanager_algorithm)
	{
		setssl_trustmanager_algorithm(getContext(), ssl_trustmanager_algorithm);
	}

	/**
	 * Set value of ssl_trustmanager_algorithm
	 * @param context
	 * @param ssl_trustmanager_algorithm
	 */
	public final void setssl_trustmanager_algorithm(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ssl_trustmanager_algorithm)
	{
		getMendixObject().setValue(context, MemberNames.ssl_trustmanager_algorithm.toString(), ssl_trustmanager_algorithm);
	}

	/**
	 * @return value of Server_Config
	 */
	public final kafka.proxies.Server getServer_Config() throws com.mendix.core.CoreException
	{
		return getServer_Config(getContext());
	}

	/**
	 * @param context
	 * @return value of Server_Config
	 */
	public final kafka.proxies.Server getServer_Config(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		kafka.proxies.Server result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Server_Config.toString());
		if (identifier != null)
			result = kafka.proxies.Server.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Server_Config
	 * @param server_config
	 */
	public final void setServer_Config(kafka.proxies.Server server_config)
	{
		setServer_Config(getContext(), server_config);
	}

	/**
	 * Set value of Server_Config
	 * @param context
	 * @param server_config
	 */
	public final void setServer_Config(com.mendix.systemwideinterfaces.core.IContext context, kafka.proxies.Server server_config)
	{
		if (server_config == null)
			getMendixObject().setValue(context, MemberNames.Server_Config.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Server_Config.toString(), server_config.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return configMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final kafka.proxies.Config that = (kafka.proxies.Config) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Kafka.Config";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
