// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package kafka.proxies;

public class Explorer
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject explorerMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Kafka.Explorer";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Explorer_Server("Kafka.Explorer_Server"),
		Explorer_Consumer("Kafka.Explorer_Consumer");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Explorer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Explorer(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject explorerMendixObject)
	{
		if (explorerMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, explorerMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.explorerMendixObject = explorerMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Explorer.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static kafka.proxies.Explorer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return kafka.proxies.Explorer.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static kafka.proxies.Explorer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new kafka.proxies.Explorer(context, mendixObject);
	}

	public static kafka.proxies.Explorer load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return kafka.proxies.Explorer.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Explorer_Server
	 */
	public final kafka.proxies.Server getExplorer_Server() throws com.mendix.core.CoreException
	{
		return getExplorer_Server(getContext());
	}

	/**
	 * @param context
	 * @return value of Explorer_Server
	 * @throws com.mendix.core.CoreException
	 */
	public final kafka.proxies.Server getExplorer_Server(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		kafka.proxies.Server result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Explorer_Server.toString());
		if (identifier != null) {
			result = kafka.proxies.Server.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Explorer_Server
	 * @param explorer_server
	 */
	public final void setExplorer_Server(kafka.proxies.Server explorer_server)
	{
		setExplorer_Server(getContext(), explorer_server);
	}

	/**
	 * Set value of Explorer_Server
	 * @param context
	 * @param explorer_server
	 */
	public final void setExplorer_Server(com.mendix.systemwideinterfaces.core.IContext context, kafka.proxies.Server explorer_server)
	{
		if (explorer_server == null) {
			getMendixObject().setValue(context, MemberNames.Explorer_Server.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Explorer_Server.toString(), explorer_server.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Explorer_Consumer
	 */
	public final kafka.proxies.Consumer getExplorer_Consumer() throws com.mendix.core.CoreException
	{
		return getExplorer_Consumer(getContext());
	}

	/**
	 * @param context
	 * @return value of Explorer_Consumer
	 * @throws com.mendix.core.CoreException
	 */
	public final kafka.proxies.Consumer getExplorer_Consumer(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		kafka.proxies.Consumer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Explorer_Consumer.toString());
		if (identifier != null) {
			result = kafka.proxies.Consumer.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Explorer_Consumer
	 * @param explorer_consumer
	 */
	public final void setExplorer_Consumer(kafka.proxies.Consumer explorer_consumer)
	{
		setExplorer_Consumer(getContext(), explorer_consumer);
	}

	/**
	 * Set value of Explorer_Consumer
	 * @param context
	 * @param explorer_consumer
	 */
	public final void setExplorer_Consumer(com.mendix.systemwideinterfaces.core.IContext context, kafka.proxies.Consumer explorer_consumer)
	{
		if (explorer_consumer == null) {
			getMendixObject().setValue(context, MemberNames.Explorer_Consumer.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Explorer_Consumer.toString(), explorer_consumer.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return explorerMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final kafka.proxies.Explorer that = (kafka.proxies.Explorer) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
