// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package kafka.proxies;

public class Header
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject headerMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Kafka.Header";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Key("Key"),
		Value("Value"),
		Header_Message("Kafka.Header_Message"),
		Header_Publisher("Kafka.Header_Publisher");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Header(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Kafka.Header"));
	}

	protected Header(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject headerMendixObject)
	{
		if (headerMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Kafka.Header", headerMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Kafka.Header");

		this.headerMendixObject = headerMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Header.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static kafka.proxies.Header initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return kafka.proxies.Header.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static kafka.proxies.Header initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new kafka.proxies.Header(context, mendixObject);
	}

	public static kafka.proxies.Header load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return kafka.proxies.Header.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Key
	 */
	public final java.lang.String getKey()
	{
		return getKey(getContext());
	}

	/**
	 * @param context
	 * @return value of Key
	 */
	public final java.lang.String getKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Key.toString());
	}

	/**
	 * Set value of Key
	 * @param key
	 */
	public final void setKey(java.lang.String key)
	{
		setKey(getContext(), key);
	}

	/**
	 * Set value of Key
	 * @param context
	 * @param key
	 */
	public final void setKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String key)
	{
		getMendixObject().setValue(context, MemberNames.Key.toString(), key);
	}

	/**
	 * @return value of Value
	 */
	public final java.lang.String getValue()
	{
		return getValue(getContext());
	}

	/**
	 * @param context
	 * @return value of Value
	 */
	public final java.lang.String getValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Value.toString());
	}

	/**
	 * Set value of Value
	 * @param value
	 */
	public final void setValue(java.lang.String value)
	{
		setValue(getContext(), value);
	}

	/**
	 * Set value of Value
	 * @param context
	 * @param value
	 */
	public final void setValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String value)
	{
		getMendixObject().setValue(context, MemberNames.Value.toString(), value);
	}

	/**
	 * @return value of Header_Message
	 */
	public final kafka.proxies.Message getHeader_Message() throws com.mendix.core.CoreException
	{
		return getHeader_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of Header_Message
	 */
	public final kafka.proxies.Message getHeader_Message(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		kafka.proxies.Message result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Header_Message.toString());
		if (identifier != null)
			result = kafka.proxies.Message.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Header_Message
	 * @param header_message
	 */
	public final void setHeader_Message(kafka.proxies.Message header_message)
	{
		setHeader_Message(getContext(), header_message);
	}

	/**
	 * Set value of Header_Message
	 * @param context
	 * @param header_message
	 */
	public final void setHeader_Message(com.mendix.systemwideinterfaces.core.IContext context, kafka.proxies.Message header_message)
	{
		if (header_message == null)
			getMendixObject().setValue(context, MemberNames.Header_Message.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Header_Message.toString(), header_message.getMendixObject().getId());
	}

	/**
	 * @return value of Header_Publisher
	 */
	public final kafka.proxies.Publisher getHeader_Publisher() throws com.mendix.core.CoreException
	{
		return getHeader_Publisher(getContext());
	}

	/**
	 * @param context
	 * @return value of Header_Publisher
	 */
	public final kafka.proxies.Publisher getHeader_Publisher(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		kafka.proxies.Publisher result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Header_Publisher.toString());
		if (identifier != null)
			result = kafka.proxies.Publisher.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Header_Publisher
	 * @param header_publisher
	 */
	public final void setHeader_Publisher(kafka.proxies.Publisher header_publisher)
	{
		setHeader_Publisher(getContext(), header_publisher);
	}

	/**
	 * Set value of Header_Publisher
	 * @param context
	 * @param header_publisher
	 */
	public final void setHeader_Publisher(com.mendix.systemwideinterfaces.core.IContext context, kafka.proxies.Publisher header_publisher)
	{
		if (header_publisher == null)
			getMendixObject().setValue(context, MemberNames.Header_Publisher.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Header_Publisher.toString(), header_publisher.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return headerMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final kafka.proxies.Header that = (kafka.proxies.Header) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Kafka.Header";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
