// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package kafka.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	/**
	 * @deprecated
	 * The default constructor of the Constants class should not be used.
	 * Use the static get methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Constants() {}

	// These are the constants for the Kafka module

	/**
	* If Kafka connections used, are so vital for your application, using the critical level can be considered.
	*/
	public static boolean getLogConsumerLostAsCritical()
	{
		return (java.lang.Boolean)Core.getConfiguration().getConstantValue("Kafka.LogConsumerLostAsCritical");
	}
}