// This file was generated by Mendix Modeler 6.10.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package alertsdemo.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the AlertsDemo module

	public static java.lang.String getAlertsTopic()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("AlertsDemo.AlertsTopic");
	}

	public static java.lang.String getProducerName()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("AlertsDemo.ProducerName");
	}
}