// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package kafkamodule.proxies;

public class KafkaConsumer
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject kafkaConsumerMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "KafkaModule.KafkaConsumer";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		KafkaConsumer_ConsumerConfig("KafkaModule.KafkaConsumer_ConsumerConfig"),
		KafkaConsumer_KafkaServer("KafkaModule.KafkaConsumer_KafkaServer");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public KafkaConsumer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "KafkaModule.KafkaConsumer"));
	}

	protected KafkaConsumer(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject kafkaConsumerMendixObject)
	{
		if (kafkaConsumerMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("KafkaModule.KafkaConsumer", kafkaConsumerMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a KafkaModule.KafkaConsumer");

		this.kafkaConsumerMendixObject = kafkaConsumerMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'KafkaConsumer.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static kafkamodule.proxies.KafkaConsumer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return kafkamodule.proxies.KafkaConsumer.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static kafkamodule.proxies.KafkaConsumer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new kafkamodule.proxies.KafkaConsumer(context, mendixObject);
	}

	public static kafkamodule.proxies.KafkaConsumer load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return kafkamodule.proxies.KafkaConsumer.initialize(context, mendixObject);
	}

	public static java.util.List<kafkamodule.proxies.KafkaConsumer> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<kafkamodule.proxies.KafkaConsumer> result = new java.util.ArrayList<kafkamodule.proxies.KafkaConsumer>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//KafkaModule.KafkaConsumer" + xpathConstraint))
			result.add(kafkamodule.proxies.KafkaConsumer.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of KafkaConsumer_ConsumerConfig
	 */
	public final kafkamodule.proxies.ConsumerConfig getKafkaConsumer_ConsumerConfig() throws com.mendix.core.CoreException
	{
		return getKafkaConsumer_ConsumerConfig(getContext());
	}

	/**
	 * @param context
	 * @return value of KafkaConsumer_ConsumerConfig
	 */
	public final kafkamodule.proxies.ConsumerConfig getKafkaConsumer_ConsumerConfig(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		kafkamodule.proxies.ConsumerConfig result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.KafkaConsumer_ConsumerConfig.toString());
		if (identifier != null)
			result = kafkamodule.proxies.ConsumerConfig.load(context, identifier);
		return result;
	}

	/**
	 * Set value of KafkaConsumer_ConsumerConfig
	 * @param kafkaconsumer_consumerconfig
	 */
	public final void setKafkaConsumer_ConsumerConfig(kafkamodule.proxies.ConsumerConfig kafkaconsumer_consumerconfig)
	{
		setKafkaConsumer_ConsumerConfig(getContext(), kafkaconsumer_consumerconfig);
	}

	/**
	 * Set value of KafkaConsumer_ConsumerConfig
	 * @param context
	 * @param kafkaconsumer_consumerconfig
	 */
	public final void setKafkaConsumer_ConsumerConfig(com.mendix.systemwideinterfaces.core.IContext context, kafkamodule.proxies.ConsumerConfig kafkaconsumer_consumerconfig)
	{
		if (kafkaconsumer_consumerconfig == null)
			getMendixObject().setValue(context, MemberNames.KafkaConsumer_ConsumerConfig.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.KafkaConsumer_ConsumerConfig.toString(), kafkaconsumer_consumerconfig.getMendixObject().getId());
	}

	/**
	 * @return value of KafkaConsumer_KafkaServer
	 */
	public final kafkamodule.proxies.KafkaServer getKafkaConsumer_KafkaServer() throws com.mendix.core.CoreException
	{
		return getKafkaConsumer_KafkaServer(getContext());
	}

	/**
	 * @param context
	 * @return value of KafkaConsumer_KafkaServer
	 */
	public final kafkamodule.proxies.KafkaServer getKafkaConsumer_KafkaServer(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		kafkamodule.proxies.KafkaServer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.KafkaConsumer_KafkaServer.toString());
		if (identifier != null)
			result = kafkamodule.proxies.KafkaServer.load(context, identifier);
		return result;
	}

	/**
	 * Set value of KafkaConsumer_KafkaServer
	 * @param kafkaconsumer_kafkaserver
	 */
	public final void setKafkaConsumer_KafkaServer(kafkamodule.proxies.KafkaServer kafkaconsumer_kafkaserver)
	{
		setKafkaConsumer_KafkaServer(getContext(), kafkaconsumer_kafkaserver);
	}

	/**
	 * Set value of KafkaConsumer_KafkaServer
	 * @param context
	 * @param kafkaconsumer_kafkaserver
	 */
	public final void setKafkaConsumer_KafkaServer(com.mendix.systemwideinterfaces.core.IContext context, kafkamodule.proxies.KafkaServer kafkaconsumer_kafkaserver)
	{
		if (kafkaconsumer_kafkaserver == null)
			getMendixObject().setValue(context, MemberNames.KafkaConsumer_KafkaServer.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.KafkaConsumer_KafkaServer.toString(), kafkaconsumer_kafkaserver.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return kafkaConsumerMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final kafkamodule.proxies.KafkaConsumer that = (kafkamodule.proxies.KafkaConsumer) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "KafkaModule.KafkaConsumer";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
