// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package kafkamodule.proxies;

public class KeyStore extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "KafkaModule.KeyStore";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Password("Password"),
		PrivateKeyPassword("PrivateKeyPassword"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		TrustStore_KeyStore("KafkaModule.TrustStore_KeyStore"),
		KeyStore_KeyStore("KafkaModule.KeyStore_KeyStore");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public KeyStore(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "KafkaModule.KeyStore"));
	}

	protected KeyStore(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject keyStoreMendixObject)
	{
		super(context, keyStoreMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("KafkaModule.KeyStore", keyStoreMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a KafkaModule.KeyStore");
	}

	/**
	 * @deprecated Use 'KeyStore.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static kafkamodule.proxies.KeyStore initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return kafkamodule.proxies.KeyStore.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static kafkamodule.proxies.KeyStore initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new kafkamodule.proxies.KeyStore(context, mendixObject);
	}

	public static kafkamodule.proxies.KeyStore load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return kafkamodule.proxies.KeyStore.initialize(context, mendixObject);
	}

	public static java.util.List<kafkamodule.proxies.KeyStore> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<kafkamodule.proxies.KeyStore> result = new java.util.ArrayList<kafkamodule.proxies.KeyStore>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//KafkaModule.KeyStore" + xpathConstraint))
			result.add(kafkamodule.proxies.KeyStore.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of Password
	 */
	public final java.lang.String getPassword()
	{
		return getPassword(getContext());
	}

	/**
	 * @param context
	 * @return value of Password
	 */
	public final java.lang.String getPassword(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Password.toString());
	}

	/**
	 * Set value of Password
	 * @param password
	 */
	public final void setPassword(java.lang.String password)
	{
		setPassword(getContext(), password);
	}

	/**
	 * Set value of Password
	 * @param context
	 * @param password
	 */
	public final void setPassword(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String password)
	{
		getMendixObject().setValue(context, MemberNames.Password.toString(), password);
	}

	/**
	 * @return value of PrivateKeyPassword
	 */
	public final java.lang.String getPrivateKeyPassword()
	{
		return getPrivateKeyPassword(getContext());
	}

	/**
	 * @param context
	 * @return value of PrivateKeyPassword
	 */
	public final java.lang.String getPrivateKeyPassword(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PrivateKeyPassword.toString());
	}

	/**
	 * Set value of PrivateKeyPassword
	 * @param privatekeypassword
	 */
	public final void setPrivateKeyPassword(java.lang.String privatekeypassword)
	{
		setPrivateKeyPassword(getContext(), privatekeypassword);
	}

	/**
	 * Set value of PrivateKeyPassword
	 * @param context
	 * @param privatekeypassword
	 */
	public final void setPrivateKeyPassword(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String privatekeypassword)
	{
		getMendixObject().setValue(context, MemberNames.PrivateKeyPassword.toString(), privatekeypassword);
	}

	/**
	 * @return value of TrustStore_KeyStore
	 */
	public final kafkamodule.proxies.KafkaServer getTrustStore_KeyStore() throws com.mendix.core.CoreException
	{
		return getTrustStore_KeyStore(getContext());
	}

	/**
	 * @param context
	 * @return value of TrustStore_KeyStore
	 */
	public final kafkamodule.proxies.KafkaServer getTrustStore_KeyStore(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		kafkamodule.proxies.KafkaServer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TrustStore_KeyStore.toString());
		if (identifier != null)
			result = kafkamodule.proxies.KafkaServer.load(context, identifier);
		return result;
	}

	/**
	 * Set value of TrustStore_KeyStore
	 * @param truststore_keystore
	 */
	public final void setTrustStore_KeyStore(kafkamodule.proxies.KafkaServer truststore_keystore)
	{
		setTrustStore_KeyStore(getContext(), truststore_keystore);
	}

	/**
	 * Set value of TrustStore_KeyStore
	 * @param context
	 * @param truststore_keystore
	 */
	public final void setTrustStore_KeyStore(com.mendix.systemwideinterfaces.core.IContext context, kafkamodule.proxies.KafkaServer truststore_keystore)
	{
		if (truststore_keystore == null)
			getMendixObject().setValue(context, MemberNames.TrustStore_KeyStore.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.TrustStore_KeyStore.toString(), truststore_keystore.getMendixObject().getId());
	}

	/**
	 * @return value of KeyStore_KeyStore
	 */
	public final kafkamodule.proxies.KafkaServer getKeyStore_KeyStore() throws com.mendix.core.CoreException
	{
		return getKeyStore_KeyStore(getContext());
	}

	/**
	 * @param context
	 * @return value of KeyStore_KeyStore
	 */
	public final kafkamodule.proxies.KafkaServer getKeyStore_KeyStore(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		kafkamodule.proxies.KafkaServer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.KeyStore_KeyStore.toString());
		if (identifier != null)
			result = kafkamodule.proxies.KafkaServer.load(context, identifier);
		return result;
	}

	/**
	 * Set value of KeyStore_KeyStore
	 * @param keystore_keystore
	 */
	public final void setKeyStore_KeyStore(kafkamodule.proxies.KafkaServer keystore_keystore)
	{
		setKeyStore_KeyStore(getContext(), keystore_keystore);
	}

	/**
	 * Set value of KeyStore_KeyStore
	 * @param context
	 * @param keystore_keystore
	 */
	public final void setKeyStore_KeyStore(com.mendix.systemwideinterfaces.core.IContext context, kafkamodule.proxies.KafkaServer keystore_keystore)
	{
		if (keystore_keystore == null)
			getMendixObject().setValue(context, MemberNames.KeyStore_KeyStore.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.KeyStore_KeyStore.toString(), keystore_keystore.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final kafkamodule.proxies.KeyStore that = (kafkamodule.proxies.KeyStore) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "KafkaModule.KeyStore";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
