// This file was generated by Mendix Modeler 7.16.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package kafkamodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the KafkaModule module
	public static void aCr_KafkaConsumer(IContext context, kafkamodule.proxies.Consumer _kafkaConsumer)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("KafkaConsumer", _kafkaConsumer == null ? null : _kafkaConsumer.getMendixObject());
			Core.execute(context, "KafkaModule.ACr_KafkaConsumer", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aCr_KafkaProducer(IContext context, kafkamodule.proxies.Producer _kafkaProducer)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("KafkaProducer", _kafkaProducer == null ? null : _kafkaProducer.getMendixObject());
			Core.execute(context, "KafkaModule.ACr_KafkaProducer", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void aCr_KafkaServer(IContext context, kafkamodule.proxies.Server _kafkaServer)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("KafkaServer", _kafkaServer == null ? null : _kafkaServer.getMendixObject());
			Core.execute(context, "KafkaModule.ACr_KafkaServer", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean bCo_Consumer(IContext context, kafkamodule.proxies.Consumer _consumer)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Consumer", _consumer == null ? null : _consumer.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "KafkaModule.BCo_Consumer", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean bCo_KeyStore(IContext context, kafkamodule.proxies.KeyStore _keyStore)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("KeyStore", _keyStore == null ? null : _keyStore.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "KafkaModule.BCo_KeyStore", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<kafkamodule.proxies.Partition> dS_GetDetailedPartitions(IContext context, kafkamodule.proxies.Topic _topic, kafkamodule.proxies.Explorer _explorer)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Topic", _topic == null ? null : _topic.getMendixObject());
			params.put("Explorer", _explorer == null ? null : _explorer.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "KafkaModule.DS_GetDetailedPartitions", params);
			java.util.List<kafkamodule.proxies.Partition> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<kafkamodule.proxies.Partition>();
				for (IMendixObject obj : objs)
					result.add(kafkamodule.proxies.Partition.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static kafkamodule.proxies.Explorer dS_GetExplorer(IContext context, kafkamodule.proxies.Server _server)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Server", _server == null ? null : _server.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "KafkaModule.DS_GetExplorer", params);
			return result == null ? null : kafkamodule.proxies.Explorer.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static kafkamodule.proxies.MessageOverview dS_GetNewMessageOverview(IContext context, kafkamodule.proxies.Partition _partition)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Partition", _partition == null ? null : _partition.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "KafkaModule.DS_GetNewMessageOverview", params);
			return result == null ? null : kafkamodule.proxies.MessageOverview.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static kafkamodule.proxies.Publisher dS_GetPublisher(IContext context, kafkamodule.proxies.Server _server)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Server", _server == null ? null : _server.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "KafkaModule.DS_GetPublisher", params);
			return result == null ? null : kafkamodule.proxies.Publisher.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<kafkamodule.proxies.Consumer> dS_GetSelectableConsumers(IContext context, kafkamodule.proxies.Server _server)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Server", _server == null ? null : _server.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "KafkaModule.DS_GetSelectableConsumers", params);
			java.util.List<kafkamodule.proxies.Consumer> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<kafkamodule.proxies.Consumer>();
				for (IMendixObject obj : objs)
					result.add(kafkamodule.proxies.Consumer.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<kafkamodule.proxies.Producer> dS_GetSelectableProducers(IContext context, kafkamodule.proxies.Server _server)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Server", _server == null ? null : _server.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "KafkaModule.DS_GetSelectableProducers", params);
			java.util.List<kafkamodule.proxies.Producer> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<kafkamodule.proxies.Producer>();
				for (IMendixObject obj : objs)
					result.add(kafkamodule.proxies.Producer.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean example_AfterStartUpConsumersMicroflow(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			return (java.lang.Boolean)Core.execute(context, "KafkaModule.Example_AfterStartUpConsumersMicroflow", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void example_OnReceiveMicroflow(IContext context, java.lang.Long _offset, java.lang.String _key, java.lang.String _value, java.lang.String _messageType)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Offset", _offset);
			params.put("Key", _key);
			params.put("Value", _value);
			params.put("MessageType", _messageType);
			Core.execute(context, "KafkaModule.Example_OnReceiveMicroflow", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_CreateNewHeader(IContext context, kafkamodule.proxies.Publisher _publisher)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Publisher", _publisher == null ? null : _publisher.getMendixObject());
			Core.execute(context, "KafkaModule.IVK_CreateNewHeader", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_PublishMessage(IContext context, kafkamodule.proxies.Publisher _publisher)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Publisher", _publisher == null ? null : _publisher.getMendixObject());
			Core.execute(context, "KafkaModule.IVK_PublishMessage", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_RetrieveMessages(IContext context, kafkamodule.proxies.MessageOverview _messageOverview, kafkamodule.proxies.Partition _partition)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("MessageOverview", _messageOverview == null ? null : _messageOverview.getMendixObject());
			params.put("Partition", _partition == null ? null : _partition.getMendixObject());
			Core.execute(context, "KafkaModule.IVK_RetrieveMessages", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_RetrieveTopics(IContext context, kafkamodule.proxies.Explorer _explorer, kafkamodule.proxies.Server _server)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Explorer", _explorer == null ? null : _explorer.getMendixObject());
			params.put("Server", _server == null ? null : _server.getMendixObject());
			Core.execute(context, "KafkaModule.IVK_RetrieveTopics", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_SaveKafkaConsumer(IContext context, kafkamodule.proxies.Consumer _kafkaConsumer)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("KafkaConsumer", _kafkaConsumer == null ? null : _kafkaConsumer.getMendixObject());
			Core.execute(context, "KafkaModule.IVK_SaveKafkaConsumer", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_SaveKafkaProducer(IContext context, kafkamodule.proxies.Producer _kafkaProducer)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("KafkaProducer", _kafkaProducer == null ? null : _kafkaProducer.getMendixObject());
			Core.execute(context, "KafkaModule.IVK_SaveKafkaProducer", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_SaveKafkaServer(IContext context, kafkamodule.proxies.Server _kafkaServer)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("KafkaServer", _kafkaServer == null ? null : _kafkaServer.getMendixObject());
			Core.execute(context, "KafkaModule.IVK_SaveKafkaServer", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	/**
	 * Stops all active Kafka connections. Use this as (part of) your 'Before shutdown' microflow.
	 */
	public static void shutdown(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "KafkaModule.Shutdown", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}