// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package alertsdemo.proxies;

public class Alert
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject alertMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AlertsDemo.Alert";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Category("Category"),
		Message("Message"),
		Alert_AlertFilterCriteria("AlertsDemo.Alert_AlertFilterCriteria");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Alert(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "AlertsDemo.Alert"));
	}

	protected Alert(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject alertMendixObject)
	{
		if (alertMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("AlertsDemo.Alert", alertMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a AlertsDemo.Alert");

		this.alertMendixObject = alertMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Alert.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static alertsdemo.proxies.Alert initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return alertsdemo.proxies.Alert.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static alertsdemo.proxies.Alert initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new alertsdemo.proxies.Alert(context, mendixObject);
	}

	public static alertsdemo.proxies.Alert load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return alertsdemo.proxies.Alert.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Category
	 */
	public final java.lang.String getCategory()
	{
		return getCategory(getContext());
	}

	/**
	 * @param context
	 * @return value of Category
	 */
	public final java.lang.String getCategory(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Category.toString());
	}

	/**
	 * Set value of Category
	 * @param category
	 */
	public final void setCategory(java.lang.String category)
	{
		setCategory(getContext(), category);
	}

	/**
	 * Set value of Category
	 * @param context
	 * @param category
	 */
	public final void setCategory(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String category)
	{
		getMendixObject().setValue(context, MemberNames.Category.toString(), category);
	}

	/**
	 * @return value of Message
	 */
	public final java.lang.String getMessage()
	{
		return getMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of Message
	 */
	public final java.lang.String getMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Message.toString());
	}

	/**
	 * Set value of Message
	 * @param message
	 */
	public final void setMessage(java.lang.String message)
	{
		setMessage(getContext(), message);
	}

	/**
	 * Set value of Message
	 * @param context
	 * @param message
	 */
	public final void setMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String message)
	{
		getMendixObject().setValue(context, MemberNames.Message.toString(), message);
	}

	/**
	 * @return value of Alert_AlertFilterCriteria
	 */
	public final alertsdemo.proxies.AlertFilterCriteria getAlert_AlertFilterCriteria() throws com.mendix.core.CoreException
	{
		return getAlert_AlertFilterCriteria(getContext());
	}

	/**
	 * @param context
	 * @return value of Alert_AlertFilterCriteria
	 */
	public final alertsdemo.proxies.AlertFilterCriteria getAlert_AlertFilterCriteria(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		alertsdemo.proxies.AlertFilterCriteria result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Alert_AlertFilterCriteria.toString());
		if (identifier != null)
			result = alertsdemo.proxies.AlertFilterCriteria.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Alert_AlertFilterCriteria
	 * @param alert_alertfiltercriteria
	 */
	public final void setAlert_AlertFilterCriteria(alertsdemo.proxies.AlertFilterCriteria alert_alertfiltercriteria)
	{
		setAlert_AlertFilterCriteria(getContext(), alert_alertfiltercriteria);
	}

	/**
	 * Set value of Alert_AlertFilterCriteria
	 * @param context
	 * @param alert_alertfiltercriteria
	 */
	public final void setAlert_AlertFilterCriteria(com.mendix.systemwideinterfaces.core.IContext context, alertsdemo.proxies.AlertFilterCriteria alert_alertfiltercriteria)
	{
		if (alert_alertfiltercriteria == null)
			getMendixObject().setValue(context, MemberNames.Alert_AlertFilterCriteria.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Alert_AlertFilterCriteria.toString(), alert_alertfiltercriteria.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return alertMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final alertsdemo.proxies.Alert that = (alertsdemo.proxies.Alert) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "AlertsDemo.Alert";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
