// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package alertsdemo.proxies;

public class AlertFilterCriteria
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject alertFilterCriteriaMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AlertsDemo.AlertFilterCriteria";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Category("Category"),
		UniqueName("UniqueName"),
		AlertFilterCriteria_Session("AlertsDemo.AlertFilterCriteria_Session");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AlertFilterCriteria(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "AlertsDemo.AlertFilterCriteria"));
	}

	protected AlertFilterCriteria(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject alertFilterCriteriaMendixObject)
	{
		if (alertFilterCriteriaMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("AlertsDemo.AlertFilterCriteria", alertFilterCriteriaMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a AlertsDemo.AlertFilterCriteria");

		this.alertFilterCriteriaMendixObject = alertFilterCriteriaMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'AlertFilterCriteria.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static alertsdemo.proxies.AlertFilterCriteria initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return alertsdemo.proxies.AlertFilterCriteria.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static alertsdemo.proxies.AlertFilterCriteria initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new alertsdemo.proxies.AlertFilterCriteria(context, mendixObject);
	}

	public static alertsdemo.proxies.AlertFilterCriteria load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return alertsdemo.proxies.AlertFilterCriteria.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Category
	 */
	public final java.lang.String getCategory()
	{
		return getCategory(getContext());
	}

	/**
	 * @param context
	 * @return value of Category
	 */
	public final java.lang.String getCategory(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Category.toString());
	}

	/**
	 * Set value of Category
	 * @param category
	 */
	public final void setCategory(java.lang.String category)
	{
		setCategory(getContext(), category);
	}

	/**
	 * Set value of Category
	 * @param context
	 * @param category
	 */
	public final void setCategory(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String category)
	{
		getMendixObject().setValue(context, MemberNames.Category.toString(), category);
	}

	/**
	 * @return value of UniqueName
	 */
	public final java.lang.String getUniqueName()
	{
		return getUniqueName(getContext());
	}

	/**
	 * @param context
	 * @return value of UniqueName
	 */
	public final java.lang.String getUniqueName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UniqueName.toString());
	}

	/**
	 * Set value of UniqueName
	 * @param uniquename
	 */
	public final void setUniqueName(java.lang.String uniquename)
	{
		setUniqueName(getContext(), uniquename);
	}

	/**
	 * Set value of UniqueName
	 * @param context
	 * @param uniquename
	 */
	public final void setUniqueName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uniquename)
	{
		getMendixObject().setValue(context, MemberNames.UniqueName.toString(), uniquename);
	}

	/**
	 * @return value of AlertFilterCriteria_Session
	 */
	public final system.proxies.Session getAlertFilterCriteria_Session() throws com.mendix.core.CoreException
	{
		return getAlertFilterCriteria_Session(getContext());
	}

	/**
	 * @param context
	 * @return value of AlertFilterCriteria_Session
	 */
	public final system.proxies.Session getAlertFilterCriteria_Session(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.Session result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AlertFilterCriteria_Session.toString());
		if (identifier != null)
			result = system.proxies.Session.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AlertFilterCriteria_Session
	 * @param alertfiltercriteria_session
	 */
	public final void setAlertFilterCriteria_Session(system.proxies.Session alertfiltercriteria_session)
	{
		setAlertFilterCriteria_Session(getContext(), alertfiltercriteria_session);
	}

	/**
	 * Set value of AlertFilterCriteria_Session
	 * @param context
	 * @param alertfiltercriteria_session
	 */
	public final void setAlertFilterCriteria_Session(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.Session alertfiltercriteria_session)
	{
		if (alertfiltercriteria_session == null)
			getMendixObject().setValue(context, MemberNames.AlertFilterCriteria_Session.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AlertFilterCriteria_Session.toString(), alertfiltercriteria_session.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return alertFilterCriteriaMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final alertsdemo.proxies.AlertFilterCriteria that = (alertsdemo.proxies.AlertFilterCriteria) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "AlertsDemo.AlertFilterCriteria";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
