// This file was generated by Mendix Modeler 6.10.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package temperaturedemo.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the TemperatureDemo module

	public static java.lang.String getCelsiusTopic()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("TemperatureDemo.CelsiusTopic");
	}

	public static java.lang.String getConsumerName()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("TemperatureDemo.ConsumerName");
	}

	public static java.lang.String getFahrenheitTopic()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("TemperatureDemo.FahrenheitTopic");
	}

	public static java.lang.String getProcessorName()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("TemperatureDemo.ProcessorName");
	}

	public static java.lang.String getProducerName()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("TemperatureDemo.ProducerName");
	}
}